# Generated by Django 4.2.28 on 2026-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', '음식/식비'), ('TRANSPORT', '교통'), ('SHOPPING', '쇼핑'), ('LIVING', '생활'), ('ETC', '기타')], default='FOOD', max_length=20),
        ),
    ]
