# Generated by Django 4.2.28 on 2026-02-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tx_type',
            field=models.CharField(choices=[('IN', '수입'), ('OUT', '지출')], default='OUT', max_length=3),
        ),
    ]
